const TOKEN_DETAILS = {
  JWT_SECRET_KEY: "BACKENDPROJECTBYNIAMUDEEN",
  REFRESH_SECRET_KEY: "BACKENDPROJECTBYNIAMUDEEN",
  ACCESS_TOKEN_EXPIRATION_TIME: "1hr",
  REFRESH_TOKEN_EXPIRATION_TIME: "30d",
};

module.exports = TOKEN_DETAILS;
